"""Execute multi-step tool plans generated by the cloud planner."""
from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from typing import Any, Awaitable, Callable

logger = logging.getLogger(__name__)

_MAX_PLAN_STEPS = 30
_STEP_RETRY_LIMIT = 1


@dataclass
class PlanStep:
    tool: str
    args: dict[str, Any]
    step_index: int
    description: str = ""


@dataclass
class StepResult:
    step_index: int
    tool: str
    status: str
    output: dict[str, Any] = field(default_factory=dict)
    error: str = ""


@dataclass
class PlanResult:
    total_steps: int
    completed_steps: int
    failed_steps: int
    step_results: list[StepResult] = field(default_factory=list)
    summary: str = ""

    @property
    def success(self) -> bool:
        return self.failed_steps == 0

    def to_dict(self) -> dict[str, Any]:
        return {
            "total_steps": self.total_steps,
            "completed_steps": self.completed_steps,
            "failed_steps": self.failed_steps,
            "success": self.success,
            "summary": self.summary,
            "steps": [
                {
                    "step": item.step_index + 1,
                    "tool": item.tool,
                    "status": item.status,
                    "error": item.error or None,
                }
                for item in self.step_results
            ],
        }


class PlanExecutor:
    """Validate and run multi-step plans against a safe tool registry."""

    def __init__(self, safe_registry: Any, allowed_tools: set[str] | None = None) -> None:
        self._registry = safe_registry
        self._allowed: set[str] = allowed_tools or safe_registry.allowed_tools

    def validate_plan(self, raw_plan: list[dict[str, Any]]) -> list[PlanStep]:
        if not isinstance(raw_plan, list) or not raw_plan:
            raise ValueError("Plan must be a non-empty list of steps.")

        steps: list[PlanStep] = []
        for index, raw_step in enumerate(raw_plan[:_MAX_PLAN_STEPS]):
            tool = str(raw_step.get("tool", "")).strip()
            args = raw_step.get("args", {})
            if not isinstance(args, dict):
                args = {}

            if not tool:
                raise ValueError(f"Step {index + 1} has no tool name.")
            if tool not in self._allowed:
                raise ValueError(
                    f"Step {index + 1}: tool '{tool}' is not in the allowed list. "
                    f"Allowed: {sorted(self._allowed)[:10]}..."
                )

            steps.append(
                PlanStep(
                    tool=tool,
                    args=args,
                    step_index=index,
                    description=str(raw_step.get("description", "") or f"{tool}({args})"),
                )
            )

        expanded = self._expand_range_steps(steps)
        if len(expanded) > _MAX_PLAN_STEPS:
            raise ValueError(f"Expanded plan has {len(expanded)} steps; max is {_MAX_PLAN_STEPS}.")
        return expanded

    async def execute(
        self,
        steps: list[PlanStep],
        *,
        on_step_progress: Callable[[int, int, str, str], Awaitable[None]] | None = None,
    ) -> PlanResult:
        total = len(steps)
        completed = 0
        failed = 0
        results: list[StepResult] = []

        for step in steps:
            if on_step_progress is not None:
                await on_step_progress(step.step_index, total, step.tool, "start")

            result = await self._execute_step_with_retry(step)
            results.append(result)

            if result.status == "ok":
                completed += 1
                if on_step_progress is not None:
                    await on_step_progress(step.step_index, total, step.tool, "done")
            else:
                failed += 1
                if on_step_progress is not None:
                    await on_step_progress(step.step_index, total, step.tool, "error")

                if "PermissionError" in result.error or "allowlist" in result.error.lower():
                    logger.error("Plan aborted at step %d due to permission policy.", step.step_index + 1)
                    break

        summary = self._build_summary(steps, results, completed, failed)
        return PlanResult(
            total_steps=total,
            completed_steps=completed,
            failed_steps=failed,
            step_results=results,
            summary=summary,
        )

    async def _execute_step_with_retry(self, step: PlanStep) -> StepResult:
        last_error = ""
        for attempt in range(_STEP_RETRY_LIMIT + 1):
            try:
                result = await self._registry.execute(step.tool, step.args)
                status = str(result.get("status", "ok")).lower()
                if status in {"ok", "success", "opened", "done", "sent", "scheduled"}:
                    return StepResult(step.step_index, step.tool, "ok", output=result)
                last_error = str(result.get("error", result.get("message", f"Tool returned status={status}")))
            except PermissionError as err:
                return StepResult(step.step_index, step.tool, "error", error=f"PermissionError: {err}")
            except Exception as err:  # noqa: BLE001
                last_error = str(err)
                if attempt < _STEP_RETRY_LIMIT:
                    continue

        return StepResult(step.step_index, step.tool, "error", error=last_error)

    @staticmethod
    def _expand_range_steps(steps: list[PlanStep]) -> list[PlanStep]:
        expanded: list[PlanStep] = []
        range_re = re.compile(r"\{(\d+)-(\d+)\}")

        for step in steps:
            expandable_key: str | None = None
            expandable_template: str | None = None

            for key, value in step.args.items():
                if isinstance(value, str) and range_re.search(value):
                    expandable_key = key
                    expandable_template = value
                    break

            if expandable_key is None or expandable_template is None:
                expanded.append(step)
                continue

            match = range_re.search(expandable_template)
            if not match:
                expanded.append(step)
                continue

            start = int(match.group(1))
            end = int(match.group(2))
            if end < start or (end - start) > 50:
                expanded.append(step)
                continue

            for number in range(start, end + 1):
                replaced = range_re.sub(str(number), expandable_template, count=1)
                new_args = {**step.args, expandable_key: replaced}
                expanded.append(
                    PlanStep(
                        tool=step.tool,
                        args=new_args,
                        step_index=len(expanded),
                        description=f"{step.tool}({replaced})",
                    )
                )

        for index, step in enumerate(expanded):
            step.step_index = index

        return expanded

    @staticmethod
    def _build_summary(
        steps: list[PlanStep],
        results: list[StepResult],
        completed: int,
        failed: int,
    ) -> str:
        total = len(steps)
        if failed == 0:
            return f"All {total} steps completed successfully."
        if completed == 0:
            return f"Plan failed: all {total} steps encountered errors."
        errors = [item for item in results if item.status == "error"]
        names = ", ".join(item.tool for item in errors[:3])
        return f"Completed {completed}/{total} steps. {failed} step(s) failed: {names}."
