from __future__ import annotations

import json
import os
import subprocess
import sys
import threading
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any

import httpx

MOCK_HOST = "127.0.0.1"
MOCK_PORT = 8099
API_HOST = "127.0.0.1"
API_PORT = 8010
API_BASE = f"http://{API_HOST}:{API_PORT}"


class MockCloudHandler(BaseHTTPRequestHandler):
    server_version = "MockCloud/1.0"

    def _read_json(self) -> dict[str, Any]:
        length = int(self.headers.get("Content-Length", "0"))
        raw = self.rfile.read(length) if length > 0 else b"{}"
        return json.loads(raw.decode("utf-8"))

    def _write_json(self, payload: dict[str, Any], status: int = 200) -> None:
        encoded = json.dumps(payload).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(encoded)))
        self.end_headers()
        self.wfile.write(encoded)

    def _write_stream(self, chunks: list[str], model: str) -> None:
        self.send_response(200)
        self.send_header("Content-Type", "text/event-stream")
        self.send_header("Cache-Control", "no-cache")
        self.send_header("Connection", "close")
        self.end_headers()

        for chunk in chunks:
            payload = {
                "id": "cmpl-mock",
                "object": "chat.completion.chunk",
                "model": model,
                "choices": [
                    {
                        "index": 0,
                        "delta": {"content": chunk},
                        "finish_reason": None,
                    }
                ],
            }
            self.wfile.write(f"data: {json.dumps(payload)}\n\n".encode("utf-8"))
            self.wfile.flush()

        done_payload = {
            "id": "cmpl-mock",
            "object": "chat.completion.chunk",
            "model": model,
            "choices": [{"index": 0, "delta": {}, "finish_reason": "stop"}],
        }
        self.wfile.write(f"data: {json.dumps(done_payload)}\n\n".encode("utf-8"))
        self.wfile.write(b"data: [DONE]\n\n")
        self.wfile.flush()

    def do_POST(self) -> None:  # noqa: N802
        if self.path != "/chat/completions":
            self._write_json({"error": "not_found"}, status=404)
            return

        body = self._read_json()
        model = str(body.get("model") or "mock-model")
        stream = bool(body.get("stream"))
        messages = body.get("messages") or []
        user_text = ""
        if isinstance(messages, list):
            for item in reversed(messages):
                if isinstance(item, dict) and item.get("role") == "user":
                    user_text = str(item.get("content") or "")
                    break

        wants_json = isinstance(body.get("response_format"), dict)
        if wants_json:
            plan_payload = {
                "steps": [
                    {
                        "tool": "search_web",
                        "args": {"query": "latest AI news", "max_results": 2},
                    },
                    {
                        "tool": "write_docx_report",
                        "args": {
                            "title": "AI News Smoke Report",
                            "content": "Generated by API smoke test.",
                            "file_name": "smoke_ai_news_report",
                        },
                    },
                ]
            }
            payload = {
                "id": "cmpl-mock-json",
                "object": "chat.completion",
                "model": model,
                "choices": [
                    {
                        "index": 0,
                        "message": {"role": "assistant", "content": json.dumps(plan_payload)},
                        "finish_reason": "stop",
                    }
                ],
                "usage": {"prompt_tokens": 10, "completion_tokens": 30, "total_tokens": 40},
            }
            self._write_json(payload)
            return

        if stream:
            if "Search results for" in user_text:
                chunks = [
                    "Top results show rapid updates in AI models and policy. ",
                    "Would you like a focused summary on regulation or model releases?",
                ]
            elif "explain" in user_text.lower() or "trade-off" in user_text.lower():
                chunks = [
                    "A practical trade-off is speed versus accuracy. ",
                    "For interactive tasks, prioritize latency; for planning, prioritize depth.",
                ]
            else:
                chunks = ["Plan created and executed successfully."]
            self._write_stream(chunks, model=model)
            return

        payload = {
            "id": "cmpl-mock",
            "object": "chat.completion",
            "model": model,
            "choices": [
                {
                    "index": 0,
                    "message": {"role": "assistant", "content": "Mock completion."},
                    "finish_reason": "stop",
                }
            ],
            "usage": {"prompt_tokens": 5, "completion_tokens": 5, "total_tokens": 10},
        }
        self._write_json(payload)

    def log_message(self, format: str, *args: Any) -> None:  # noqa: A003
        return


def wait_until_ready(url: str, timeout_seconds: float) -> None:
    deadline = time.time() + timeout_seconds
    with httpx.Client(timeout=2.0) as client:
        while time.time() < deadline:
            try:
                response = client.get(url)
                if response.status_code == 200:
                    return
            except httpx.HTTPError:
                pass
            time.sleep(0.25)
    raise RuntimeError(f"Timed out waiting for {url}")


def run_chat(client: httpx.Client, message: str) -> dict[str, Any]:
    response = client.post(
        f"{API_BASE}/v1/chat",
        json={"message": message, "auto_speak": False},
        timeout=60.0,
    )
    response.raise_for_status()

    final_event: dict[str, Any] | None = None
    for raw_line in response.text.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        event = json.loads(line)
        if event.get("type") == "error":
            raise RuntimeError(f"Stream error: {event}")
        if event.get("type") == "final":
            final_event = event

    if final_event is None:
        raise RuntimeError(f"No final event for message: {message}")
    return final_event


def main() -> int:
    mock_server = ThreadingHTTPServer((MOCK_HOST, MOCK_PORT), MockCloudHandler)
    mock_thread = threading.Thread(target=mock_server.serve_forever, daemon=True)
    mock_thread.start()

    repo_root = Path(__file__).resolve().parents[1]
    backend_root = repo_root / "jarvis-backend"

    env = os.environ.copy()
    env["JARVIS_CLOUD_API_KEY"] = "smoke-key"
    env["JARVIS_CLOUD_BASE_URL"] = f"http://{MOCK_HOST}:{MOCK_PORT}"
    env["JARVIS_CLOUD_MODEL"] = "mock-groq"
    env["JARVIS_CLOUD_ENABLED"] = "1"

    backend = subprocess.Popen(
        [
            sys.executable,
            "-m",
            "uvicorn",
            "app.main:app",
            "--host",
            API_HOST,
            "--port",
            str(API_PORT),
            "--log-level",
            "warning",
        ],
        cwd=str(backend_root),
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )

    try:
        wait_until_ready(f"{API_BASE}/health", timeout_seconds=25)
        with httpx.Client(timeout=60.0) as client:
            reasoning = run_chat(client, "Explain the trade-off between speed and accuracy for assistants.")
            search = run_chat(client, "Search latest AI headlines and summarize.")
            multistep = run_chat(
                client,
                "Open Notepad then create a Word report named smoke_ai_news_report after searching latest AI news.",
            )

        events = {
            "cloud_reasoning": reasoning,
            "cloud_search": search,
            "cloud_multistep_and_docx": multistep,
        }

        for name, event in events.items():
            speech_policy = event.get("speech_policy")
            if not isinstance(speech_policy, dict):
                raise RuntimeError(f"Missing speech_policy in final event for {name}: {event}")

        report_path = Path.home() / "Documents" / "JarvisReports" / "smoke_ai_news_report.docx"
        print(
            "multistep-final:",
            json.dumps(
                {
                    "text": multistep.get("text"),
                    "speech_policy": multistep.get("speech_policy"),
                    "last_tool_outcome": multistep.get("last_tool_outcome"),
                },
                ensure_ascii=False,
            ),
        )
        if not report_path.exists():
            raise RuntimeError(f"Expected report file was not created: {report_path}")

        print("Smoke succeeded:")
        for name, event in events.items():
            payload = {
                "text": event.get("text"),
                "speech_policy": event.get("speech_policy"),
                "last_tool_outcome": event.get("last_tool_outcome"),
            }
            print(f"- {name}: {json.dumps(payload, ensure_ascii=False)}")
        print(f"- report_file: {report_path}")
        return 0
    finally:
        if backend.poll() is None:
            backend.terminate()
            try:
                backend.wait(timeout=10)
            except subprocess.TimeoutExpired:
                backend.kill()
        mock_server.shutdown()
        mock_server.server_close()


if __name__ == "__main__":
    raise SystemExit(main())
